### ISSUE TITLE
Aws api gateway android get specific data from web based

### ISSUE THREAD

**Issue by JustonJ99** [xfsnow/android#2]
Hi, so far I followed your API-gateway petstore demo is working fine because it is open API and able to show data on my android phone.

However, If I have a website which allows the user to log in and check the sales record based on the ID. What is the guideline to configure the API-gateway? Should I use the private API?

**Comment by xfsnow** [comment]
If your API is used to serve users from Internet, you still need public API Gateway.
You can use API Gateway Lambda Authorizers to adopt to your logged users.
https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-use-lambda-authorizer.html

If you integrate Cognito as authentication method, you can also use IAM authentication.
https://aws.amazon.com/premiumsupport/knowledge-center/iam-authentication-api-gateway/
